--- 
build-frontend-master: 
  only: 
    - master
  script: 
    - env
    - "docker build -t ci/frontend:alpha ."
    - "docker stop frontendalpha && docker rm frontendalpha"
    - "docker run --name frontendalpha -p 80:80 -d --rm ci/frontend:alpha"