build-images:
 only: 
   - master
 script: 
   - "docker build -t ci/frontend:alpha ."
delete-container: 
 only: 
   - master
 script: 
   - "docker stop frontendalpha && docker rm frontendalpha"
 allow_failure: true
run-container:
 only :
   - master
 script:
   - "docker run --name frontendalpha -p 80:80 -d --rm ci/frontend:alpha"
 allow_failure: true